# cSpell: disable
graduates:
  # 0x04
  "nicolas-wickens":
    fullName: Nicolas Wickens
    course: WDX180
    part: 1
    cohort: "0x04"
    date: 05/01/2026
  "karina-repinska-churkina":
    fullName: Karina Repinska-Churkina
    course: WDX180
    part: 1
    cohort: "0x04"
    date: 01/01/2026
  "nurettin-bayhan":
    fullName: Nurettin Bayhan
    course: WDX180
    part: 1
    cohort: "0x04"
    date: 26/12/2025
  "mac-thartcher-mboufeh-nchadje":
    fullName: Mac Thartcher Mboufeh NCHADJE
    course: WDX180
    part: 1
    cohort: "0x04"
    date: 04/02/2026
  # 0x03
  "mubashra-irshad":
    fullName: Mubashra Irshad
    course: WDX180
    part: 1
    cohort: "0x03"
    date: 19/05/2025
  "nelly-laurene-tumukunde":
    fullName: Nelly Laurene TUMUKUNDE
    course: WDX180
    part: 1
    cohort: "0x03"
    date: 03/01/2025
  "gregory-tsitses":
    fullName: Gregory Tsitses
    course: WDX180
    part: 1
    cohort: "0x03"
    date: 06/01/2025
  "catherine-gousetis":
    fullName: Catherine Gousetis
    course: WDX180
    part: 1
    cohort: "0x03"
    date: "10/01/2025"
  # 0x02
  "mary-richelle-dogra":
    fullName: Mary Richelle Dogra
    course: WDX180
    part: 3
    cohort: "0x02"
    date: 01/07/2024
  "anna-vorona":
    fullName: Anna Vorona
    course: WDX180
    part: 2
    cohort: "0x02"
    date: 29/03/2024
  "kokh-olexandr":
    fullName: Kokh Olexandr
    course: WDX180
    part: 3
    cohort: "0x02"
    date: 01/07/2024
  "kountouras-leon":
    fullName: "Leon Kountouras"
    course: WDX180
    part: 3
    cohort: "0x02"
    date: 01/07/2024
  "ozgur-ozbek":
    fullName: "Özgür Özbek"
    course: WDX180
    part: 3
    cohort: "0x02"
    date: 01/07/2024
  "mawugbenyo-aziakonou":
    fullName: Mawugbenyo AZIAKONOU
    course: WDX180
    part: 1
    cohort: "0x02"
    date: 24/12/2023
  "iasonas-grammatikopoulos":
    fullName: Iasonas Grammatikopoulos
    course: WDX180
    part: 1
    cohort: "0x02"
    date: 24/12/2023
  "beh-solo-kone":
    fullName: Beh Solo Kone
    course: WDX180
    part: 1
    cohort: "0x02"
    date: 24/12/2023
  # React Workshop: Q12024
  "maria-karavazaki":
    fullName: Maria Karavazaki
    course: React Workshop Q1:2024
    cohort: "React Workshop Q1:2024"
    date: 29/03/2024
  "aris-giotis":
    fullName: Aris Giotis
    course: React Workshop Q1:2024
    cohort: "React Workshop Q1:2024"
    date: 29/03/2024
cohorts:
  "0x04":
    leadInstructor:
      fullName: Kostas Minaidis
      linkedIn: kostas-minaidis
    teachingAssistant:
      fullName: Asteris Giannoudis
      linkedIn: asteris-giannoudis
  "0x03":
    leadInstructor:
      fullName: Kostas Minaidis
      linkedIn: kostas-minaidis
    teachingAssistant:
      fullName: Asteris Giannoudis
      linkedIn: asteris-giannoudis
  "0x02":
    leadInstructor:
      fullName: Kostas Minaidis
      linkedIn: kostas-minaidis
    teachingAssistant:
      fullName: Asteris Giannoudis
      linkedIn: asteris-giannoudis
  "React Workshop Q1:2024":
    leadInstructor:
      fullName: Kostas Minaidis
      linkedIn: kostas-minaidis
    teachingAssistant:
      fullName: Asteris Giannoudis
      linkedIn: asteris-giannoudis
staff:
  cofounders:
    - Abed Hamami:
      fullName: Abed Hamami
      linkedIn: "abedhamami"
    - Sohail Haqyar:
      fullName: Sohail Haqyar
      linkedIn: "sohail-haqyar"
